name: absa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.0
  - numpy=1.18.1
  - scipy
  - tqdm
  - pytorch=1.10.0
  - transformers=4.23.1
  - pip
  - pip:
    - benepar